# Generated by Django 2.2.1 on 2019-05-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politic',
            name='detail_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='politic',
            name='detail_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='politic',
            name='prev_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='politic',
            name='prev_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='politic',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='politic',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
