# Generated by Django 2.2.1 on 2019-05-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_artcile_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artcile',
        ),
    ]
