# Generated by Django 2.2.1 on 2019-05-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
