# Generated by Django 2.2.1 on 2019-06-05 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_politicsandсonfidentiality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Tags')),
            ],
        ),
    ]
