# Generated by Django 2.2.1 on 2019-06-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_art_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='art',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
