# Generated by Django 2.2.1 on 2019-06-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20190605_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('href', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True)),
                ('more_text', models.TextField(blank=True)),
                ('el_one', models.ManyToManyField(to='account.Article')),
            ],
        ),
    ]
