# Generated by Django 2.2.1 on 2019-06-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_mainpage_mainslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='el_one',
            field=models.ManyToManyField(blank=True, to='account.Article'),
        ),
    ]
