# Generated by Django 2.2.1 on 2019-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('img', models.ImageField(upload_to='')),
                ('href', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
